//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpAsCompanyApp.SonService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SonService.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name Sehir_Ismi from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IlceListesi", ReplyAction="*")]
        HelpAsCompanyApp.SonService.IlceListesiResponse IlceListesi(HelpAsCompanyApp.SonService.IlceListesiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IlceListesi", ReplyAction="*")]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.IlceListesiResponse> IlceListesiAsync(HelpAsCompanyApp.SonService.IlceListesiRequest request);
        
        // CODEGEN: Generating message contract since element name SehirListesiResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SehirListesi", ReplyAction="*")]
        HelpAsCompanyApp.SonService.SehirListesiResponse SehirListesi(HelpAsCompanyApp.SonService.SehirListesiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SehirListesi", ReplyAction="*")]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.SehirListesiResponse> SehirListesiAsync(HelpAsCompanyApp.SonService.SehirListesiRequest request);
        
        // CODEGEN: Generating message contract since element name AlanListesiResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AlanListesi", ReplyAction="*")]
        HelpAsCompanyApp.SonService.AlanListesiResponse AlanListesi(HelpAsCompanyApp.SonService.AlanListesiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AlanListesi", ReplyAction="*")]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.AlanListesiResponse> AlanListesiAsync(HelpAsCompanyApp.SonService.AlanListesiRequest request);
        
        // CODEGEN: Generating message contract since element name Alan_Ismi from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AltAlanListesi", ReplyAction="*")]
        HelpAsCompanyApp.SonService.AltAlanListesiResponse AltAlanListesi(HelpAsCompanyApp.SonService.AltAlanListesiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AltAlanListesi", ReplyAction="*")]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.AltAlanListesiResponse> AltAlanListesiAsync(HelpAsCompanyApp.SonService.AltAlanListesiRequest request);
        
        // CODEGEN: Generating message contract since element name HaberListeleResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HaberListele", ReplyAction="*")]
        HelpAsCompanyApp.SonService.HaberListeleResponse HaberListele(HelpAsCompanyApp.SonService.HaberListeleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HaberListele", ReplyAction="*")]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.HaberListeleResponse> HaberListeleAsync(HelpAsCompanyApp.SonService.HaberListeleRequest request);
        
        // CODEGEN: Generating message contract since element name baslik from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HaberEkle", ReplyAction="*")]
        HelpAsCompanyApp.SonService.HaberEkleResponse HaberEkle(HelpAsCompanyApp.SonService.HaberEkleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HaberEkle", ReplyAction="*")]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.HaberEkleResponse> HaberEkleAsync(HelpAsCompanyApp.SonService.HaberEkleRequest request);
        
        // CODEGEN: Generating message contract since element name HaberSilResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HaberSil", ReplyAction="*")]
        HelpAsCompanyApp.SonService.HaberSilResponse HaberSil(HelpAsCompanyApp.SonService.HaberSilRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HaberSil", ReplyAction="*")]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.HaberSilResponse> HaberSilAsync(HelpAsCompanyApp.SonService.HaberSilRequest request);
        
        // CODEGEN: Generating message contract since element name haber_baslik from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HaberGüncelle", ReplyAction="*")]
        HelpAsCompanyApp.SonService.HaberGüncelleResponse HaberGüncelle(HelpAsCompanyApp.SonService.HaberGüncelleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HaberGüncelle", ReplyAction="*")]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.HaberGüncelleResponse> HaberGüncelleAsync(HelpAsCompanyApp.SonService.HaberGüncelleRequest request);
        
        // CODEGEN: Generating message contract since element name Usta_ListeleResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Usta_Listele", ReplyAction="*")]
        HelpAsCompanyApp.SonService.Usta_ListeleResponse Usta_Listele(HelpAsCompanyApp.SonService.Usta_ListeleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Usta_Listele", ReplyAction="*")]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.Usta_ListeleResponse> Usta_ListeleAsync(HelpAsCompanyApp.SonService.Usta_ListeleRequest request);
        
        // CODEGEN: Generating message contract since element name AlanIsmiDonderResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AlanIsmiDonder", ReplyAction="*")]
        HelpAsCompanyApp.SonService.AlanIsmiDonderResponse AlanIsmiDonder(HelpAsCompanyApp.SonService.AlanIsmiDonderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AlanIsmiDonder", ReplyAction="*")]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.AlanIsmiDonderResponse> AlanIsmiDonderAsync(HelpAsCompanyApp.SonService.AlanIsmiDonderRequest request);
        
        // CODEGEN: Generating message contract since element name AltAlanIsmiDonderResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AltAlanIsmiDonder", ReplyAction="*")]
        HelpAsCompanyApp.SonService.AltAlanIsmiDonderResponse AltAlanIsmiDonder(HelpAsCompanyApp.SonService.AltAlanIsmiDonderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AltAlanIsmiDonder", ReplyAction="*")]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.AltAlanIsmiDonderResponse> AltAlanIsmiDonderAsync(HelpAsCompanyApp.SonService.AltAlanIsmiDonderRequest request);
        
        // CODEGEN: Generating message contract since element name SehirIsmiDonderResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SehirIsmiDonder", ReplyAction="*")]
        HelpAsCompanyApp.SonService.SehirIsmiDonderResponse SehirIsmiDonder(HelpAsCompanyApp.SonService.SehirIsmiDonderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SehirIsmiDonder", ReplyAction="*")]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.SehirIsmiDonderResponse> SehirIsmiDonderAsync(HelpAsCompanyApp.SonService.SehirIsmiDonderRequest request);
        
        // CODEGEN: Generating message contract since element name IlceIsmiDonderResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IlceIsmiDonder", ReplyAction="*")]
        HelpAsCompanyApp.SonService.IlceIsmiDonderResponse IlceIsmiDonder(HelpAsCompanyApp.SonService.IlceIsmiDonderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IlceIsmiDonder", ReplyAction="*")]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.IlceIsmiDonderResponse> IlceIsmiDonderAsync(HelpAsCompanyApp.SonService.IlceIsmiDonderRequest request);
        
        // CODEGEN: Generating message contract since element name usta_ismi from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Usta_Ekle", ReplyAction="*")]
        HelpAsCompanyApp.SonService.Usta_EkleResponse Usta_Ekle(HelpAsCompanyApp.SonService.Usta_EkleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Usta_Ekle", ReplyAction="*")]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.Usta_EkleResponse> Usta_EkleAsync(HelpAsCompanyApp.SonService.Usta_EkleRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IlceListesiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IlceListesi", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.IlceListesiRequestBody Body;
        
        public IlceListesiRequest() {
        }
        
        public IlceListesiRequest(HelpAsCompanyApp.SonService.IlceListesiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IlceListesiRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Sehir_Ismi;
        
        public IlceListesiRequestBody() {
        }
        
        public IlceListesiRequestBody(string Sehir_Ismi) {
            this.Sehir_Ismi = Sehir_Ismi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IlceListesiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IlceListesiResponse", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.IlceListesiResponseBody Body;
        
        public IlceListesiResponse() {
        }
        
        public IlceListesiResponse(HelpAsCompanyApp.SonService.IlceListesiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IlceListesiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IlceListesiResult;
        
        public IlceListesiResponseBody() {
        }
        
        public IlceListesiResponseBody(string IlceListesiResult) {
            this.IlceListesiResult = IlceListesiResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SehirListesiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SehirListesi", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.SehirListesiRequestBody Body;
        
        public SehirListesiRequest() {
        }
        
        public SehirListesiRequest(HelpAsCompanyApp.SonService.SehirListesiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SehirListesiRequestBody {
        
        public SehirListesiRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SehirListesiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SehirListesiResponse", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.SehirListesiResponseBody Body;
        
        public SehirListesiResponse() {
        }
        
        public SehirListesiResponse(HelpAsCompanyApp.SonService.SehirListesiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SehirListesiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SehirListesiResult;
        
        public SehirListesiResponseBody() {
        }
        
        public SehirListesiResponseBody(string SehirListesiResult) {
            this.SehirListesiResult = SehirListesiResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AlanListesiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AlanListesi", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.AlanListesiRequestBody Body;
        
        public AlanListesiRequest() {
        }
        
        public AlanListesiRequest(HelpAsCompanyApp.SonService.AlanListesiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AlanListesiRequestBody {
        
        public AlanListesiRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AlanListesiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AlanListesiResponse", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.AlanListesiResponseBody Body;
        
        public AlanListesiResponse() {
        }
        
        public AlanListesiResponse(HelpAsCompanyApp.SonService.AlanListesiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AlanListesiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AlanListesiResult;
        
        public AlanListesiResponseBody() {
        }
        
        public AlanListesiResponseBody(string AlanListesiResult) {
            this.AlanListesiResult = AlanListesiResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AltAlanListesiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AltAlanListesi", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.AltAlanListesiRequestBody Body;
        
        public AltAlanListesiRequest() {
        }
        
        public AltAlanListesiRequest(HelpAsCompanyApp.SonService.AltAlanListesiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AltAlanListesiRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Alan_Ismi;
        
        public AltAlanListesiRequestBody() {
        }
        
        public AltAlanListesiRequestBody(string Alan_Ismi) {
            this.Alan_Ismi = Alan_Ismi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AltAlanListesiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AltAlanListesiResponse", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.AltAlanListesiResponseBody Body;
        
        public AltAlanListesiResponse() {
        }
        
        public AltAlanListesiResponse(HelpAsCompanyApp.SonService.AltAlanListesiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AltAlanListesiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AltAlanListesiResult;
        
        public AltAlanListesiResponseBody() {
        }
        
        public AltAlanListesiResponseBody(string AltAlanListesiResult) {
            this.AltAlanListesiResult = AltAlanListesiResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HaberListeleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HaberListele", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.HaberListeleRequestBody Body;
        
        public HaberListeleRequest() {
        }
        
        public HaberListeleRequest(HelpAsCompanyApp.SonService.HaberListeleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HaberListeleRequestBody {
        
        public HaberListeleRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HaberListeleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HaberListeleResponse", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.HaberListeleResponseBody Body;
        
        public HaberListeleResponse() {
        }
        
        public HaberListeleResponse(HelpAsCompanyApp.SonService.HaberListeleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HaberListeleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HaberListeleResult;
        
        public HaberListeleResponseBody() {
        }
        
        public HaberListeleResponseBody(string HaberListeleResult) {
            this.HaberListeleResult = HaberListeleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HaberEkleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HaberEkle", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.HaberEkleRequestBody Body;
        
        public HaberEkleRequest() {
        }
        
        public HaberEkleRequest(HelpAsCompanyApp.SonService.HaberEkleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HaberEkleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string baslik;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string icerik;
        
        public HaberEkleRequestBody() {
        }
        
        public HaberEkleRequestBody(string baslik, string icerik) {
            this.baslik = baslik;
            this.icerik = icerik;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HaberEkleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HaberEkleResponse", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.HaberEkleResponseBody Body;
        
        public HaberEkleResponse() {
        }
        
        public HaberEkleResponse(HelpAsCompanyApp.SonService.HaberEkleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HaberEkleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HaberEkleResult;
        
        public HaberEkleResponseBody() {
        }
        
        public HaberEkleResponseBody(string HaberEkleResult) {
            this.HaberEkleResult = HaberEkleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HaberSilRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HaberSil", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.HaberSilRequestBody Body;
        
        public HaberSilRequest() {
        }
        
        public HaberSilRequest(HelpAsCompanyApp.SonService.HaberSilRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HaberSilRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int haber_id;
        
        public HaberSilRequestBody() {
        }
        
        public HaberSilRequestBody(int haber_id) {
            this.haber_id = haber_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HaberSilResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HaberSilResponse", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.HaberSilResponseBody Body;
        
        public HaberSilResponse() {
        }
        
        public HaberSilResponse(HelpAsCompanyApp.SonService.HaberSilResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HaberSilResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HaberSilResult;
        
        public HaberSilResponseBody() {
        }
        
        public HaberSilResponseBody(string HaberSilResult) {
            this.HaberSilResult = HaberSilResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HaberGüncelleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HaberGüncelle", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.HaberGüncelleRequestBody Body;
        
        public HaberGüncelleRequest() {
        }
        
        public HaberGüncelleRequest(HelpAsCompanyApp.SonService.HaberGüncelleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HaberGüncelleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int haber_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string haber_baslik;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string haber_icerik;
        
        public HaberGüncelleRequestBody() {
        }
        
        public HaberGüncelleRequestBody(int haber_id, string haber_baslik, string haber_icerik) {
            this.haber_id = haber_id;
            this.haber_baslik = haber_baslik;
            this.haber_icerik = haber_icerik;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HaberGüncelleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HaberGüncelleResponse", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.HaberGüncelleResponseBody Body;
        
        public HaberGüncelleResponse() {
        }
        
        public HaberGüncelleResponse(HelpAsCompanyApp.SonService.HaberGüncelleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HaberGüncelleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HaberGüncelleResult;
        
        public HaberGüncelleResponseBody() {
        }
        
        public HaberGüncelleResponseBody(string HaberGüncelleResult) {
            this.HaberGüncelleResult = HaberGüncelleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Usta_ListeleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Usta_Listele", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.Usta_ListeleRequestBody Body;
        
        public Usta_ListeleRequest() {
        }
        
        public Usta_ListeleRequest(HelpAsCompanyApp.SonService.Usta_ListeleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Usta_ListeleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ALAN_ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ALTALAN_ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int SEHIR_ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int ILCE_ID;
        
        public Usta_ListeleRequestBody() {
        }
        
        public Usta_ListeleRequestBody(int ALAN_ID, int ALTALAN_ID, int SEHIR_ID, int ILCE_ID) {
            this.ALAN_ID = ALAN_ID;
            this.ALTALAN_ID = ALTALAN_ID;
            this.SEHIR_ID = SEHIR_ID;
            this.ILCE_ID = ILCE_ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Usta_ListeleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Usta_ListeleResponse", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.Usta_ListeleResponseBody Body;
        
        public Usta_ListeleResponse() {
        }
        
        public Usta_ListeleResponse(HelpAsCompanyApp.SonService.Usta_ListeleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Usta_ListeleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Usta_ListeleResult;
        
        public Usta_ListeleResponseBody() {
        }
        
        public Usta_ListeleResponseBody(string Usta_ListeleResult) {
            this.Usta_ListeleResult = Usta_ListeleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AlanIsmiDonderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AlanIsmiDonder", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.AlanIsmiDonderRequestBody Body;
        
        public AlanIsmiDonderRequest() {
        }
        
        public AlanIsmiDonderRequest(HelpAsCompanyApp.SonService.AlanIsmiDonderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AlanIsmiDonderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int alanid;
        
        public AlanIsmiDonderRequestBody() {
        }
        
        public AlanIsmiDonderRequestBody(int alanid) {
            this.alanid = alanid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AlanIsmiDonderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AlanIsmiDonderResponse", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.AlanIsmiDonderResponseBody Body;
        
        public AlanIsmiDonderResponse() {
        }
        
        public AlanIsmiDonderResponse(HelpAsCompanyApp.SonService.AlanIsmiDonderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AlanIsmiDonderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AlanIsmiDonderResult;
        
        public AlanIsmiDonderResponseBody() {
        }
        
        public AlanIsmiDonderResponseBody(string AlanIsmiDonderResult) {
            this.AlanIsmiDonderResult = AlanIsmiDonderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AltAlanIsmiDonderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AltAlanIsmiDonder", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.AltAlanIsmiDonderRequestBody Body;
        
        public AltAlanIsmiDonderRequest() {
        }
        
        public AltAlanIsmiDonderRequest(HelpAsCompanyApp.SonService.AltAlanIsmiDonderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AltAlanIsmiDonderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int altalanid;
        
        public AltAlanIsmiDonderRequestBody() {
        }
        
        public AltAlanIsmiDonderRequestBody(int altalanid) {
            this.altalanid = altalanid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AltAlanIsmiDonderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AltAlanIsmiDonderResponse", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.AltAlanIsmiDonderResponseBody Body;
        
        public AltAlanIsmiDonderResponse() {
        }
        
        public AltAlanIsmiDonderResponse(HelpAsCompanyApp.SonService.AltAlanIsmiDonderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AltAlanIsmiDonderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AltAlanIsmiDonderResult;
        
        public AltAlanIsmiDonderResponseBody() {
        }
        
        public AltAlanIsmiDonderResponseBody(string AltAlanIsmiDonderResult) {
            this.AltAlanIsmiDonderResult = AltAlanIsmiDonderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SehirIsmiDonderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SehirIsmiDonder", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.SehirIsmiDonderRequestBody Body;
        
        public SehirIsmiDonderRequest() {
        }
        
        public SehirIsmiDonderRequest(HelpAsCompanyApp.SonService.SehirIsmiDonderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SehirIsmiDonderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sehirid;
        
        public SehirIsmiDonderRequestBody() {
        }
        
        public SehirIsmiDonderRequestBody(int sehirid) {
            this.sehirid = sehirid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SehirIsmiDonderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SehirIsmiDonderResponse", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.SehirIsmiDonderResponseBody Body;
        
        public SehirIsmiDonderResponse() {
        }
        
        public SehirIsmiDonderResponse(HelpAsCompanyApp.SonService.SehirIsmiDonderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SehirIsmiDonderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SehirIsmiDonderResult;
        
        public SehirIsmiDonderResponseBody() {
        }
        
        public SehirIsmiDonderResponseBody(string SehirIsmiDonderResult) {
            this.SehirIsmiDonderResult = SehirIsmiDonderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IlceIsmiDonderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IlceIsmiDonder", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.IlceIsmiDonderRequestBody Body;
        
        public IlceIsmiDonderRequest() {
        }
        
        public IlceIsmiDonderRequest(HelpAsCompanyApp.SonService.IlceIsmiDonderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IlceIsmiDonderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ilceid;
        
        public IlceIsmiDonderRequestBody() {
        }
        
        public IlceIsmiDonderRequestBody(int ilceid) {
            this.ilceid = ilceid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IlceIsmiDonderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IlceIsmiDonderResponse", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.IlceIsmiDonderResponseBody Body;
        
        public IlceIsmiDonderResponse() {
        }
        
        public IlceIsmiDonderResponse(HelpAsCompanyApp.SonService.IlceIsmiDonderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IlceIsmiDonderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IlceIsmiDonderResult;
        
        public IlceIsmiDonderResponseBody() {
        }
        
        public IlceIsmiDonderResponseBody(string IlceIsmiDonderResult) {
            this.IlceIsmiDonderResult = IlceIsmiDonderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Usta_EkleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Usta_Ekle", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.Usta_EkleRequestBody Body;
        
        public Usta_EkleRequest() {
        }
        
        public Usta_EkleRequest(HelpAsCompanyApp.SonService.Usta_EkleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Usta_EkleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int alan_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int sehir_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int ilce_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string usta_ismi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string usta_soyismi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string usta_tel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string usta_mail;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int usta_puan;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int usta_musaitlik;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public int altalan_id;
        
        public Usta_EkleRequestBody() {
        }
        
        public Usta_EkleRequestBody(int alan_id, int sehir_id, int ilce_id, string usta_ismi, string usta_soyismi, string usta_tel, string usta_mail, int usta_puan, int usta_musaitlik, int altalan_id) {
            this.alan_id = alan_id;
            this.sehir_id = sehir_id;
            this.ilce_id = ilce_id;
            this.usta_ismi = usta_ismi;
            this.usta_soyismi = usta_soyismi;
            this.usta_tel = usta_tel;
            this.usta_mail = usta_mail;
            this.usta_puan = usta_puan;
            this.usta_musaitlik = usta_musaitlik;
            this.altalan_id = altalan_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Usta_EkleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Usta_EkleResponse", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.Usta_EkleResponseBody Body;
        
        public Usta_EkleResponse() {
        }
        
        public Usta_EkleResponse(HelpAsCompanyApp.SonService.Usta_EkleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Usta_EkleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Usta_EkleResult;
        
        public Usta_EkleResponseBody() {
        }
        
        public Usta_EkleResponseBody(string Usta_EkleResult) {
            this.Usta_EkleResult = Usta_EkleResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : HelpAsCompanyApp.SonService.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<HelpAsCompanyApp.SonService.WebService1Soap>, HelpAsCompanyApp.SonService.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelpAsCompanyApp.SonService.IlceListesiResponse HelpAsCompanyApp.SonService.WebService1Soap.IlceListesi(HelpAsCompanyApp.SonService.IlceListesiRequest request) {
            return base.Channel.IlceListesi(request);
        }
        
        public string IlceListesi(string Sehir_Ismi) {
            HelpAsCompanyApp.SonService.IlceListesiRequest inValue = new HelpAsCompanyApp.SonService.IlceListesiRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.IlceListesiRequestBody();
            inValue.Body.Sehir_Ismi = Sehir_Ismi;
            HelpAsCompanyApp.SonService.IlceListesiResponse retVal = ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).IlceListesi(inValue);
            return retVal.Body.IlceListesiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.IlceListesiResponse> HelpAsCompanyApp.SonService.WebService1Soap.IlceListesiAsync(HelpAsCompanyApp.SonService.IlceListesiRequest request) {
            return base.Channel.IlceListesiAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.IlceListesiResponse> IlceListesiAsync(string Sehir_Ismi) {
            HelpAsCompanyApp.SonService.IlceListesiRequest inValue = new HelpAsCompanyApp.SonService.IlceListesiRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.IlceListesiRequestBody();
            inValue.Body.Sehir_Ismi = Sehir_Ismi;
            return ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).IlceListesiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelpAsCompanyApp.SonService.SehirListesiResponse HelpAsCompanyApp.SonService.WebService1Soap.SehirListesi(HelpAsCompanyApp.SonService.SehirListesiRequest request) {
            return base.Channel.SehirListesi(request);
        }
        
        public string SehirListesi() {
            HelpAsCompanyApp.SonService.SehirListesiRequest inValue = new HelpAsCompanyApp.SonService.SehirListesiRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.SehirListesiRequestBody();
            HelpAsCompanyApp.SonService.SehirListesiResponse retVal = ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).SehirListesi(inValue);
            return retVal.Body.SehirListesiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.SehirListesiResponse> HelpAsCompanyApp.SonService.WebService1Soap.SehirListesiAsync(HelpAsCompanyApp.SonService.SehirListesiRequest request) {
            return base.Channel.SehirListesiAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.SehirListesiResponse> SehirListesiAsync() {
            HelpAsCompanyApp.SonService.SehirListesiRequest inValue = new HelpAsCompanyApp.SonService.SehirListesiRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.SehirListesiRequestBody();
            return ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).SehirListesiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelpAsCompanyApp.SonService.AlanListesiResponse HelpAsCompanyApp.SonService.WebService1Soap.AlanListesi(HelpAsCompanyApp.SonService.AlanListesiRequest request) {
            return base.Channel.AlanListesi(request);
        }
        
        public string AlanListesi() {
            HelpAsCompanyApp.SonService.AlanListesiRequest inValue = new HelpAsCompanyApp.SonService.AlanListesiRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.AlanListesiRequestBody();
            HelpAsCompanyApp.SonService.AlanListesiResponse retVal = ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).AlanListesi(inValue);
            return retVal.Body.AlanListesiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.AlanListesiResponse> HelpAsCompanyApp.SonService.WebService1Soap.AlanListesiAsync(HelpAsCompanyApp.SonService.AlanListesiRequest request) {
            return base.Channel.AlanListesiAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.AlanListesiResponse> AlanListesiAsync() {
            HelpAsCompanyApp.SonService.AlanListesiRequest inValue = new HelpAsCompanyApp.SonService.AlanListesiRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.AlanListesiRequestBody();
            return ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).AlanListesiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelpAsCompanyApp.SonService.AltAlanListesiResponse HelpAsCompanyApp.SonService.WebService1Soap.AltAlanListesi(HelpAsCompanyApp.SonService.AltAlanListesiRequest request) {
            return base.Channel.AltAlanListesi(request);
        }
        
        public string AltAlanListesi(string Alan_Ismi) {
            HelpAsCompanyApp.SonService.AltAlanListesiRequest inValue = new HelpAsCompanyApp.SonService.AltAlanListesiRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.AltAlanListesiRequestBody();
            inValue.Body.Alan_Ismi = Alan_Ismi;
            HelpAsCompanyApp.SonService.AltAlanListesiResponse retVal = ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).AltAlanListesi(inValue);
            return retVal.Body.AltAlanListesiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.AltAlanListesiResponse> HelpAsCompanyApp.SonService.WebService1Soap.AltAlanListesiAsync(HelpAsCompanyApp.SonService.AltAlanListesiRequest request) {
            return base.Channel.AltAlanListesiAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.AltAlanListesiResponse> AltAlanListesiAsync(string Alan_Ismi) {
            HelpAsCompanyApp.SonService.AltAlanListesiRequest inValue = new HelpAsCompanyApp.SonService.AltAlanListesiRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.AltAlanListesiRequestBody();
            inValue.Body.Alan_Ismi = Alan_Ismi;
            return ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).AltAlanListesiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelpAsCompanyApp.SonService.HaberListeleResponse HelpAsCompanyApp.SonService.WebService1Soap.HaberListele(HelpAsCompanyApp.SonService.HaberListeleRequest request) {
            return base.Channel.HaberListele(request);
        }
        
        public string HaberListele() {
            HelpAsCompanyApp.SonService.HaberListeleRequest inValue = new HelpAsCompanyApp.SonService.HaberListeleRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.HaberListeleRequestBody();
            HelpAsCompanyApp.SonService.HaberListeleResponse retVal = ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).HaberListele(inValue);
            return retVal.Body.HaberListeleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.HaberListeleResponse> HelpAsCompanyApp.SonService.WebService1Soap.HaberListeleAsync(HelpAsCompanyApp.SonService.HaberListeleRequest request) {
            return base.Channel.HaberListeleAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.HaberListeleResponse> HaberListeleAsync() {
            HelpAsCompanyApp.SonService.HaberListeleRequest inValue = new HelpAsCompanyApp.SonService.HaberListeleRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.HaberListeleRequestBody();
            return ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).HaberListeleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelpAsCompanyApp.SonService.HaberEkleResponse HelpAsCompanyApp.SonService.WebService1Soap.HaberEkle(HelpAsCompanyApp.SonService.HaberEkleRequest request) {
            return base.Channel.HaberEkle(request);
        }
        
        public string HaberEkle(string baslik, string icerik) {
            HelpAsCompanyApp.SonService.HaberEkleRequest inValue = new HelpAsCompanyApp.SonService.HaberEkleRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.HaberEkleRequestBody();
            inValue.Body.baslik = baslik;
            inValue.Body.icerik = icerik;
            HelpAsCompanyApp.SonService.HaberEkleResponse retVal = ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).HaberEkle(inValue);
            return retVal.Body.HaberEkleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.HaberEkleResponse> HelpAsCompanyApp.SonService.WebService1Soap.HaberEkleAsync(HelpAsCompanyApp.SonService.HaberEkleRequest request) {
            return base.Channel.HaberEkleAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.HaberEkleResponse> HaberEkleAsync(string baslik, string icerik) {
            HelpAsCompanyApp.SonService.HaberEkleRequest inValue = new HelpAsCompanyApp.SonService.HaberEkleRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.HaberEkleRequestBody();
            inValue.Body.baslik = baslik;
            inValue.Body.icerik = icerik;
            return ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).HaberEkleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelpAsCompanyApp.SonService.HaberSilResponse HelpAsCompanyApp.SonService.WebService1Soap.HaberSil(HelpAsCompanyApp.SonService.HaberSilRequest request) {
            return base.Channel.HaberSil(request);
        }
        
        public string HaberSil(int haber_id) {
            HelpAsCompanyApp.SonService.HaberSilRequest inValue = new HelpAsCompanyApp.SonService.HaberSilRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.HaberSilRequestBody();
            inValue.Body.haber_id = haber_id;
            HelpAsCompanyApp.SonService.HaberSilResponse retVal = ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).HaberSil(inValue);
            return retVal.Body.HaberSilResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.HaberSilResponse> HelpAsCompanyApp.SonService.WebService1Soap.HaberSilAsync(HelpAsCompanyApp.SonService.HaberSilRequest request) {
            return base.Channel.HaberSilAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.HaberSilResponse> HaberSilAsync(int haber_id) {
            HelpAsCompanyApp.SonService.HaberSilRequest inValue = new HelpAsCompanyApp.SonService.HaberSilRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.HaberSilRequestBody();
            inValue.Body.haber_id = haber_id;
            return ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).HaberSilAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelpAsCompanyApp.SonService.HaberGüncelleResponse HelpAsCompanyApp.SonService.WebService1Soap.HaberGüncelle(HelpAsCompanyApp.SonService.HaberGüncelleRequest request) {
            return base.Channel.HaberGüncelle(request);
        }
        
        public string HaberGüncelle(int haber_id, string haber_baslik, string haber_icerik) {
            HelpAsCompanyApp.SonService.HaberGüncelleRequest inValue = new HelpAsCompanyApp.SonService.HaberGüncelleRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.HaberGüncelleRequestBody();
            inValue.Body.haber_id = haber_id;
            inValue.Body.haber_baslik = haber_baslik;
            inValue.Body.haber_icerik = haber_icerik;
            HelpAsCompanyApp.SonService.HaberGüncelleResponse retVal = ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).HaberGüncelle(inValue);
            return retVal.Body.HaberGüncelleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.HaberGüncelleResponse> HelpAsCompanyApp.SonService.WebService1Soap.HaberGüncelleAsync(HelpAsCompanyApp.SonService.HaberGüncelleRequest request) {
            return base.Channel.HaberGüncelleAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.HaberGüncelleResponse> HaberGüncelleAsync(int haber_id, string haber_baslik, string haber_icerik) {
            HelpAsCompanyApp.SonService.HaberGüncelleRequest inValue = new HelpAsCompanyApp.SonService.HaberGüncelleRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.HaberGüncelleRequestBody();
            inValue.Body.haber_id = haber_id;
            inValue.Body.haber_baslik = haber_baslik;
            inValue.Body.haber_icerik = haber_icerik;
            return ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).HaberGüncelleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelpAsCompanyApp.SonService.Usta_ListeleResponse HelpAsCompanyApp.SonService.WebService1Soap.Usta_Listele(HelpAsCompanyApp.SonService.Usta_ListeleRequest request) {
            return base.Channel.Usta_Listele(request);
        }
        
        public string Usta_Listele(int ALAN_ID, int ALTALAN_ID, int SEHIR_ID, int ILCE_ID) {
            HelpAsCompanyApp.SonService.Usta_ListeleRequest inValue = new HelpAsCompanyApp.SonService.Usta_ListeleRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.Usta_ListeleRequestBody();
            inValue.Body.ALAN_ID = ALAN_ID;
            inValue.Body.ALTALAN_ID = ALTALAN_ID;
            inValue.Body.SEHIR_ID = SEHIR_ID;
            inValue.Body.ILCE_ID = ILCE_ID;
            HelpAsCompanyApp.SonService.Usta_ListeleResponse retVal = ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).Usta_Listele(inValue);
            return retVal.Body.Usta_ListeleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.Usta_ListeleResponse> HelpAsCompanyApp.SonService.WebService1Soap.Usta_ListeleAsync(HelpAsCompanyApp.SonService.Usta_ListeleRequest request) {
            return base.Channel.Usta_ListeleAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.Usta_ListeleResponse> Usta_ListeleAsync(int ALAN_ID, int ALTALAN_ID, int SEHIR_ID, int ILCE_ID) {
            HelpAsCompanyApp.SonService.Usta_ListeleRequest inValue = new HelpAsCompanyApp.SonService.Usta_ListeleRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.Usta_ListeleRequestBody();
            inValue.Body.ALAN_ID = ALAN_ID;
            inValue.Body.ALTALAN_ID = ALTALAN_ID;
            inValue.Body.SEHIR_ID = SEHIR_ID;
            inValue.Body.ILCE_ID = ILCE_ID;
            return ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).Usta_ListeleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelpAsCompanyApp.SonService.AlanIsmiDonderResponse HelpAsCompanyApp.SonService.WebService1Soap.AlanIsmiDonder(HelpAsCompanyApp.SonService.AlanIsmiDonderRequest request) {
            return base.Channel.AlanIsmiDonder(request);
        }
        
        public string AlanIsmiDonder(int alanid) {
            HelpAsCompanyApp.SonService.AlanIsmiDonderRequest inValue = new HelpAsCompanyApp.SonService.AlanIsmiDonderRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.AlanIsmiDonderRequestBody();
            inValue.Body.alanid = alanid;
            HelpAsCompanyApp.SonService.AlanIsmiDonderResponse retVal = ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).AlanIsmiDonder(inValue);
            return retVal.Body.AlanIsmiDonderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.AlanIsmiDonderResponse> HelpAsCompanyApp.SonService.WebService1Soap.AlanIsmiDonderAsync(HelpAsCompanyApp.SonService.AlanIsmiDonderRequest request) {
            return base.Channel.AlanIsmiDonderAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.AlanIsmiDonderResponse> AlanIsmiDonderAsync(int alanid) {
            HelpAsCompanyApp.SonService.AlanIsmiDonderRequest inValue = new HelpAsCompanyApp.SonService.AlanIsmiDonderRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.AlanIsmiDonderRequestBody();
            inValue.Body.alanid = alanid;
            return ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).AlanIsmiDonderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelpAsCompanyApp.SonService.AltAlanIsmiDonderResponse HelpAsCompanyApp.SonService.WebService1Soap.AltAlanIsmiDonder(HelpAsCompanyApp.SonService.AltAlanIsmiDonderRequest request) {
            return base.Channel.AltAlanIsmiDonder(request);
        }
        
        public string AltAlanIsmiDonder(int altalanid) {
            HelpAsCompanyApp.SonService.AltAlanIsmiDonderRequest inValue = new HelpAsCompanyApp.SonService.AltAlanIsmiDonderRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.AltAlanIsmiDonderRequestBody();
            inValue.Body.altalanid = altalanid;
            HelpAsCompanyApp.SonService.AltAlanIsmiDonderResponse retVal = ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).AltAlanIsmiDonder(inValue);
            return retVal.Body.AltAlanIsmiDonderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.AltAlanIsmiDonderResponse> HelpAsCompanyApp.SonService.WebService1Soap.AltAlanIsmiDonderAsync(HelpAsCompanyApp.SonService.AltAlanIsmiDonderRequest request) {
            return base.Channel.AltAlanIsmiDonderAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.AltAlanIsmiDonderResponse> AltAlanIsmiDonderAsync(int altalanid) {
            HelpAsCompanyApp.SonService.AltAlanIsmiDonderRequest inValue = new HelpAsCompanyApp.SonService.AltAlanIsmiDonderRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.AltAlanIsmiDonderRequestBody();
            inValue.Body.altalanid = altalanid;
            return ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).AltAlanIsmiDonderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelpAsCompanyApp.SonService.SehirIsmiDonderResponse HelpAsCompanyApp.SonService.WebService1Soap.SehirIsmiDonder(HelpAsCompanyApp.SonService.SehirIsmiDonderRequest request) {
            return base.Channel.SehirIsmiDonder(request);
        }
        
        public string SehirIsmiDonder(int sehirid) {
            HelpAsCompanyApp.SonService.SehirIsmiDonderRequest inValue = new HelpAsCompanyApp.SonService.SehirIsmiDonderRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.SehirIsmiDonderRequestBody();
            inValue.Body.sehirid = sehirid;
            HelpAsCompanyApp.SonService.SehirIsmiDonderResponse retVal = ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).SehirIsmiDonder(inValue);
            return retVal.Body.SehirIsmiDonderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.SehirIsmiDonderResponse> HelpAsCompanyApp.SonService.WebService1Soap.SehirIsmiDonderAsync(HelpAsCompanyApp.SonService.SehirIsmiDonderRequest request) {
            return base.Channel.SehirIsmiDonderAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.SehirIsmiDonderResponse> SehirIsmiDonderAsync(int sehirid) {
            HelpAsCompanyApp.SonService.SehirIsmiDonderRequest inValue = new HelpAsCompanyApp.SonService.SehirIsmiDonderRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.SehirIsmiDonderRequestBody();
            inValue.Body.sehirid = sehirid;
            return ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).SehirIsmiDonderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelpAsCompanyApp.SonService.IlceIsmiDonderResponse HelpAsCompanyApp.SonService.WebService1Soap.IlceIsmiDonder(HelpAsCompanyApp.SonService.IlceIsmiDonderRequest request) {
            return base.Channel.IlceIsmiDonder(request);
        }
        
        public string IlceIsmiDonder(int ilceid) {
            HelpAsCompanyApp.SonService.IlceIsmiDonderRequest inValue = new HelpAsCompanyApp.SonService.IlceIsmiDonderRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.IlceIsmiDonderRequestBody();
            inValue.Body.ilceid = ilceid;
            HelpAsCompanyApp.SonService.IlceIsmiDonderResponse retVal = ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).IlceIsmiDonder(inValue);
            return retVal.Body.IlceIsmiDonderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.IlceIsmiDonderResponse> HelpAsCompanyApp.SonService.WebService1Soap.IlceIsmiDonderAsync(HelpAsCompanyApp.SonService.IlceIsmiDonderRequest request) {
            return base.Channel.IlceIsmiDonderAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.IlceIsmiDonderResponse> IlceIsmiDonderAsync(int ilceid) {
            HelpAsCompanyApp.SonService.IlceIsmiDonderRequest inValue = new HelpAsCompanyApp.SonService.IlceIsmiDonderRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.IlceIsmiDonderRequestBody();
            inValue.Body.ilceid = ilceid;
            return ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).IlceIsmiDonderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelpAsCompanyApp.SonService.Usta_EkleResponse HelpAsCompanyApp.SonService.WebService1Soap.Usta_Ekle(HelpAsCompanyApp.SonService.Usta_EkleRequest request) {
            return base.Channel.Usta_Ekle(request);
        }
        
        public string Usta_Ekle(int alan_id, int sehir_id, int ilce_id, string usta_ismi, string usta_soyismi, string usta_tel, string usta_mail, int usta_puan, int usta_musaitlik, int altalan_id) {
            HelpAsCompanyApp.SonService.Usta_EkleRequest inValue = new HelpAsCompanyApp.SonService.Usta_EkleRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.Usta_EkleRequestBody();
            inValue.Body.alan_id = alan_id;
            inValue.Body.sehir_id = sehir_id;
            inValue.Body.ilce_id = ilce_id;
            inValue.Body.usta_ismi = usta_ismi;
            inValue.Body.usta_soyismi = usta_soyismi;
            inValue.Body.usta_tel = usta_tel;
            inValue.Body.usta_mail = usta_mail;
            inValue.Body.usta_puan = usta_puan;
            inValue.Body.usta_musaitlik = usta_musaitlik;
            inValue.Body.altalan_id = altalan_id;
            HelpAsCompanyApp.SonService.Usta_EkleResponse retVal = ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).Usta_Ekle(inValue);
            return retVal.Body.Usta_EkleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.Usta_EkleResponse> HelpAsCompanyApp.SonService.WebService1Soap.Usta_EkleAsync(HelpAsCompanyApp.SonService.Usta_EkleRequest request) {
            return base.Channel.Usta_EkleAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.Usta_EkleResponse> Usta_EkleAsync(int alan_id, int sehir_id, int ilce_id, string usta_ismi, string usta_soyismi, string usta_tel, string usta_mail, int usta_puan, int usta_musaitlik, int altalan_id) {
            HelpAsCompanyApp.SonService.Usta_EkleRequest inValue = new HelpAsCompanyApp.SonService.Usta_EkleRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.Usta_EkleRequestBody();
            inValue.Body.alan_id = alan_id;
            inValue.Body.sehir_id = sehir_id;
            inValue.Body.ilce_id = ilce_id;
            inValue.Body.usta_ismi = usta_ismi;
            inValue.Body.usta_soyismi = usta_soyismi;
            inValue.Body.usta_tel = usta_tel;
            inValue.Body.usta_mail = usta_mail;
            inValue.Body.usta_puan = usta_puan;
            inValue.Body.usta_musaitlik = usta_musaitlik;
            inValue.Body.altalan_id = altalan_id;
            return ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).Usta_EkleAsync(inValue);
        }
    }
}
