//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpAsCompanyApp.SonService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SonService.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name Sehir_Ismi from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IlceListesi", ReplyAction="*")]
        HelpAsCompanyApp.SonService.IlceListesiResponse IlceListesi(HelpAsCompanyApp.SonService.IlceListesiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IlceListesi", ReplyAction="*")]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.IlceListesiResponse> IlceListesiAsync(HelpAsCompanyApp.SonService.IlceListesiRequest request);
        
        // CODEGEN: Generating message contract since element name SehirListesiResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SehirListesi", ReplyAction="*")]
        HelpAsCompanyApp.SonService.SehirListesiResponse SehirListesi(HelpAsCompanyApp.SonService.SehirListesiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SehirListesi", ReplyAction="*")]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.SehirListesiResponse> SehirListesiAsync(HelpAsCompanyApp.SonService.SehirListesiRequest request);
        
        // CODEGEN: Generating message contract since element name AlanListesiResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AlanListesi", ReplyAction="*")]
        HelpAsCompanyApp.SonService.AlanListesiResponse AlanListesi(HelpAsCompanyApp.SonService.AlanListesiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AlanListesi", ReplyAction="*")]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.AlanListesiResponse> AlanListesiAsync(HelpAsCompanyApp.SonService.AlanListesiRequest request);
        
        // CODEGEN: Generating message contract since element name Alan_Ismi from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AltAlanListesi", ReplyAction="*")]
        HelpAsCompanyApp.SonService.AltAlanListesiResponse AltAlanListesi(HelpAsCompanyApp.SonService.AltAlanListesiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AltAlanListesi", ReplyAction="*")]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.AltAlanListesiResponse> AltAlanListesiAsync(HelpAsCompanyApp.SonService.AltAlanListesiRequest request);
        
        // CODEGEN: Generating message contract since element name HaberListeleResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HaberListele", ReplyAction="*")]
        HelpAsCompanyApp.SonService.HaberListeleResponse HaberListele(HelpAsCompanyApp.SonService.HaberListeleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HaberListele", ReplyAction="*")]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.HaberListeleResponse> HaberListeleAsync(HelpAsCompanyApp.SonService.HaberListeleRequest request);
        
        // CODEGEN: Generating message contract since element name baslik from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HaberEkle", ReplyAction="*")]
        HelpAsCompanyApp.SonService.HaberEkleResponse HaberEkle(HelpAsCompanyApp.SonService.HaberEkleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HaberEkle", ReplyAction="*")]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.HaberEkleResponse> HaberEkleAsync(HelpAsCompanyApp.SonService.HaberEkleRequest request);
        
        // CODEGEN: Generating message contract since element name HaberSilResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HaberSil", ReplyAction="*")]
        HelpAsCompanyApp.SonService.HaberSilResponse HaberSil(HelpAsCompanyApp.SonService.HaberSilRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HaberSil", ReplyAction="*")]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.HaberSilResponse> HaberSilAsync(HelpAsCompanyApp.SonService.HaberSilRequest request);
        
        // CODEGEN: Generating message contract since element name haber_baslik from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HaberGüncelle", ReplyAction="*")]
        HelpAsCompanyApp.SonService.HaberGüncelleResponse HaberGüncelle(HelpAsCompanyApp.SonService.HaberGüncelleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HaberGüncelle", ReplyAction="*")]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.HaberGüncelleResponse> HaberGüncelleAsync(HelpAsCompanyApp.SonService.HaberGüncelleRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IlceListesiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IlceListesi", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.IlceListesiRequestBody Body;
        
        public IlceListesiRequest() {
        }
        
        public IlceListesiRequest(HelpAsCompanyApp.SonService.IlceListesiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IlceListesiRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Sehir_Ismi;
        
        public IlceListesiRequestBody() {
        }
        
        public IlceListesiRequestBody(string Sehir_Ismi) {
            this.Sehir_Ismi = Sehir_Ismi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IlceListesiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IlceListesiResponse", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.IlceListesiResponseBody Body;
        
        public IlceListesiResponse() {
        }
        
        public IlceListesiResponse(HelpAsCompanyApp.SonService.IlceListesiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IlceListesiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IlceListesiResult;
        
        public IlceListesiResponseBody() {
        }
        
        public IlceListesiResponseBody(string IlceListesiResult) {
            this.IlceListesiResult = IlceListesiResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SehirListesiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SehirListesi", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.SehirListesiRequestBody Body;
        
        public SehirListesiRequest() {
        }
        
        public SehirListesiRequest(HelpAsCompanyApp.SonService.SehirListesiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SehirListesiRequestBody {
        
        public SehirListesiRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SehirListesiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SehirListesiResponse", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.SehirListesiResponseBody Body;
        
        public SehirListesiResponse() {
        }
        
        public SehirListesiResponse(HelpAsCompanyApp.SonService.SehirListesiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SehirListesiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SehirListesiResult;
        
        public SehirListesiResponseBody() {
        }
        
        public SehirListesiResponseBody(string SehirListesiResult) {
            this.SehirListesiResult = SehirListesiResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AlanListesiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AlanListesi", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.AlanListesiRequestBody Body;
        
        public AlanListesiRequest() {
        }
        
        public AlanListesiRequest(HelpAsCompanyApp.SonService.AlanListesiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AlanListesiRequestBody {
        
        public AlanListesiRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AlanListesiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AlanListesiResponse", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.AlanListesiResponseBody Body;
        
        public AlanListesiResponse() {
        }
        
        public AlanListesiResponse(HelpAsCompanyApp.SonService.AlanListesiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AlanListesiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AlanListesiResult;
        
        public AlanListesiResponseBody() {
        }
        
        public AlanListesiResponseBody(string AlanListesiResult) {
            this.AlanListesiResult = AlanListesiResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AltAlanListesiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AltAlanListesi", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.AltAlanListesiRequestBody Body;
        
        public AltAlanListesiRequest() {
        }
        
        public AltAlanListesiRequest(HelpAsCompanyApp.SonService.AltAlanListesiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AltAlanListesiRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Alan_Ismi;
        
        public AltAlanListesiRequestBody() {
        }
        
        public AltAlanListesiRequestBody(string Alan_Ismi) {
            this.Alan_Ismi = Alan_Ismi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AltAlanListesiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AltAlanListesiResponse", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.AltAlanListesiResponseBody Body;
        
        public AltAlanListesiResponse() {
        }
        
        public AltAlanListesiResponse(HelpAsCompanyApp.SonService.AltAlanListesiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AltAlanListesiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AltAlanListesiResult;
        
        public AltAlanListesiResponseBody() {
        }
        
        public AltAlanListesiResponseBody(string AltAlanListesiResult) {
            this.AltAlanListesiResult = AltAlanListesiResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HaberListeleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HaberListele", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.HaberListeleRequestBody Body;
        
        public HaberListeleRequest() {
        }
        
        public HaberListeleRequest(HelpAsCompanyApp.SonService.HaberListeleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HaberListeleRequestBody {
        
        public HaberListeleRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HaberListeleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HaberListeleResponse", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.HaberListeleResponseBody Body;
        
        public HaberListeleResponse() {
        }
        
        public HaberListeleResponse(HelpAsCompanyApp.SonService.HaberListeleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HaberListeleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HaberListeleResult;
        
        public HaberListeleResponseBody() {
        }
        
        public HaberListeleResponseBody(string HaberListeleResult) {
            this.HaberListeleResult = HaberListeleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HaberEkleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HaberEkle", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.HaberEkleRequestBody Body;
        
        public HaberEkleRequest() {
        }
        
        public HaberEkleRequest(HelpAsCompanyApp.SonService.HaberEkleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HaberEkleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string baslik;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string icerik;
        
        public HaberEkleRequestBody() {
        }
        
        public HaberEkleRequestBody(string baslik, string icerik) {
            this.baslik = baslik;
            this.icerik = icerik;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HaberEkleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HaberEkleResponse", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.HaberEkleResponseBody Body;
        
        public HaberEkleResponse() {
        }
        
        public HaberEkleResponse(HelpAsCompanyApp.SonService.HaberEkleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HaberEkleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HaberEkleResult;
        
        public HaberEkleResponseBody() {
        }
        
        public HaberEkleResponseBody(string HaberEkleResult) {
            this.HaberEkleResult = HaberEkleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HaberSilRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HaberSil", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.HaberSilRequestBody Body;
        
        public HaberSilRequest() {
        }
        
        public HaberSilRequest(HelpAsCompanyApp.SonService.HaberSilRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HaberSilRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int haber_id;
        
        public HaberSilRequestBody() {
        }
        
        public HaberSilRequestBody(int haber_id) {
            this.haber_id = haber_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HaberSilResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HaberSilResponse", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.HaberSilResponseBody Body;
        
        public HaberSilResponse() {
        }
        
        public HaberSilResponse(HelpAsCompanyApp.SonService.HaberSilResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HaberSilResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HaberSilResult;
        
        public HaberSilResponseBody() {
        }
        
        public HaberSilResponseBody(string HaberSilResult) {
            this.HaberSilResult = HaberSilResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HaberGüncelleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HaberGüncelle", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.HaberGüncelleRequestBody Body;
        
        public HaberGüncelleRequest() {
        }
        
        public HaberGüncelleRequest(HelpAsCompanyApp.SonService.HaberGüncelleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HaberGüncelleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int haber_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string haber_baslik;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string haber_icerik;
        
        public HaberGüncelleRequestBody() {
        }
        
        public HaberGüncelleRequestBody(int haber_id, string haber_baslik, string haber_icerik) {
            this.haber_id = haber_id;
            this.haber_baslik = haber_baslik;
            this.haber_icerik = haber_icerik;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HaberGüncelleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HaberGüncelleResponse", Namespace="http://tempuri.org/", Order=0)]
        public HelpAsCompanyApp.SonService.HaberGüncelleResponseBody Body;
        
        public HaberGüncelleResponse() {
        }
        
        public HaberGüncelleResponse(HelpAsCompanyApp.SonService.HaberGüncelleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HaberGüncelleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HaberGüncelleResult;
        
        public HaberGüncelleResponseBody() {
        }
        
        public HaberGüncelleResponseBody(string HaberGüncelleResult) {
            this.HaberGüncelleResult = HaberGüncelleResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : HelpAsCompanyApp.SonService.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<HelpAsCompanyApp.SonService.WebService1Soap>, HelpAsCompanyApp.SonService.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelpAsCompanyApp.SonService.IlceListesiResponse HelpAsCompanyApp.SonService.WebService1Soap.IlceListesi(HelpAsCompanyApp.SonService.IlceListesiRequest request) {
            return base.Channel.IlceListesi(request);
        }
        
        public string IlceListesi(string Sehir_Ismi) {
            HelpAsCompanyApp.SonService.IlceListesiRequest inValue = new HelpAsCompanyApp.SonService.IlceListesiRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.IlceListesiRequestBody();
            inValue.Body.Sehir_Ismi = Sehir_Ismi;
            HelpAsCompanyApp.SonService.IlceListesiResponse retVal = ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).IlceListesi(inValue);
            return retVal.Body.IlceListesiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.IlceListesiResponse> HelpAsCompanyApp.SonService.WebService1Soap.IlceListesiAsync(HelpAsCompanyApp.SonService.IlceListesiRequest request) {
            return base.Channel.IlceListesiAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.IlceListesiResponse> IlceListesiAsync(string Sehir_Ismi) {
            HelpAsCompanyApp.SonService.IlceListesiRequest inValue = new HelpAsCompanyApp.SonService.IlceListesiRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.IlceListesiRequestBody();
            inValue.Body.Sehir_Ismi = Sehir_Ismi;
            return ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).IlceListesiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelpAsCompanyApp.SonService.SehirListesiResponse HelpAsCompanyApp.SonService.WebService1Soap.SehirListesi(HelpAsCompanyApp.SonService.SehirListesiRequest request) {
            return base.Channel.SehirListesi(request);
        }
        
        public string SehirListesi() {
            HelpAsCompanyApp.SonService.SehirListesiRequest inValue = new HelpAsCompanyApp.SonService.SehirListesiRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.SehirListesiRequestBody();
            HelpAsCompanyApp.SonService.SehirListesiResponse retVal = ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).SehirListesi(inValue);
            return retVal.Body.SehirListesiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.SehirListesiResponse> HelpAsCompanyApp.SonService.WebService1Soap.SehirListesiAsync(HelpAsCompanyApp.SonService.SehirListesiRequest request) {
            return base.Channel.SehirListesiAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.SehirListesiResponse> SehirListesiAsync() {
            HelpAsCompanyApp.SonService.SehirListesiRequest inValue = new HelpAsCompanyApp.SonService.SehirListesiRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.SehirListesiRequestBody();
            return ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).SehirListesiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelpAsCompanyApp.SonService.AlanListesiResponse HelpAsCompanyApp.SonService.WebService1Soap.AlanListesi(HelpAsCompanyApp.SonService.AlanListesiRequest request) {
            return base.Channel.AlanListesi(request);
        }
        
        public string AlanListesi() {
            HelpAsCompanyApp.SonService.AlanListesiRequest inValue = new HelpAsCompanyApp.SonService.AlanListesiRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.AlanListesiRequestBody();
            HelpAsCompanyApp.SonService.AlanListesiResponse retVal = ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).AlanListesi(inValue);
            return retVal.Body.AlanListesiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.AlanListesiResponse> HelpAsCompanyApp.SonService.WebService1Soap.AlanListesiAsync(HelpAsCompanyApp.SonService.AlanListesiRequest request) {
            return base.Channel.AlanListesiAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.AlanListesiResponse> AlanListesiAsync() {
            HelpAsCompanyApp.SonService.AlanListesiRequest inValue = new HelpAsCompanyApp.SonService.AlanListesiRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.AlanListesiRequestBody();
            return ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).AlanListesiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelpAsCompanyApp.SonService.AltAlanListesiResponse HelpAsCompanyApp.SonService.WebService1Soap.AltAlanListesi(HelpAsCompanyApp.SonService.AltAlanListesiRequest request) {
            return base.Channel.AltAlanListesi(request);
        }
        
        public string AltAlanListesi(string Alan_Ismi) {
            HelpAsCompanyApp.SonService.AltAlanListesiRequest inValue = new HelpAsCompanyApp.SonService.AltAlanListesiRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.AltAlanListesiRequestBody();
            inValue.Body.Alan_Ismi = Alan_Ismi;
            HelpAsCompanyApp.SonService.AltAlanListesiResponse retVal = ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).AltAlanListesi(inValue);
            return retVal.Body.AltAlanListesiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.AltAlanListesiResponse> HelpAsCompanyApp.SonService.WebService1Soap.AltAlanListesiAsync(HelpAsCompanyApp.SonService.AltAlanListesiRequest request) {
            return base.Channel.AltAlanListesiAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.AltAlanListesiResponse> AltAlanListesiAsync(string Alan_Ismi) {
            HelpAsCompanyApp.SonService.AltAlanListesiRequest inValue = new HelpAsCompanyApp.SonService.AltAlanListesiRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.AltAlanListesiRequestBody();
            inValue.Body.Alan_Ismi = Alan_Ismi;
            return ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).AltAlanListesiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelpAsCompanyApp.SonService.HaberListeleResponse HelpAsCompanyApp.SonService.WebService1Soap.HaberListele(HelpAsCompanyApp.SonService.HaberListeleRequest request) {
            return base.Channel.HaberListele(request);
        }
        
        public string HaberListele() {
            HelpAsCompanyApp.SonService.HaberListeleRequest inValue = new HelpAsCompanyApp.SonService.HaberListeleRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.HaberListeleRequestBody();
            HelpAsCompanyApp.SonService.HaberListeleResponse retVal = ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).HaberListele(inValue);
            return retVal.Body.HaberListeleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.HaberListeleResponse> HelpAsCompanyApp.SonService.WebService1Soap.HaberListeleAsync(HelpAsCompanyApp.SonService.HaberListeleRequest request) {
            return base.Channel.HaberListeleAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.HaberListeleResponse> HaberListeleAsync() {
            HelpAsCompanyApp.SonService.HaberListeleRequest inValue = new HelpAsCompanyApp.SonService.HaberListeleRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.HaberListeleRequestBody();
            return ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).HaberListeleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelpAsCompanyApp.SonService.HaberEkleResponse HelpAsCompanyApp.SonService.WebService1Soap.HaberEkle(HelpAsCompanyApp.SonService.HaberEkleRequest request) {
            return base.Channel.HaberEkle(request);
        }
        
        public string HaberEkle(string baslik, string icerik) {
            HelpAsCompanyApp.SonService.HaberEkleRequest inValue = new HelpAsCompanyApp.SonService.HaberEkleRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.HaberEkleRequestBody();
            inValue.Body.baslik = baslik;
            inValue.Body.icerik = icerik;
            HelpAsCompanyApp.SonService.HaberEkleResponse retVal = ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).HaberEkle(inValue);
            return retVal.Body.HaberEkleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.HaberEkleResponse> HelpAsCompanyApp.SonService.WebService1Soap.HaberEkleAsync(HelpAsCompanyApp.SonService.HaberEkleRequest request) {
            return base.Channel.HaberEkleAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.HaberEkleResponse> HaberEkleAsync(string baslik, string icerik) {
            HelpAsCompanyApp.SonService.HaberEkleRequest inValue = new HelpAsCompanyApp.SonService.HaberEkleRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.HaberEkleRequestBody();
            inValue.Body.baslik = baslik;
            inValue.Body.icerik = icerik;
            return ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).HaberEkleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelpAsCompanyApp.SonService.HaberSilResponse HelpAsCompanyApp.SonService.WebService1Soap.HaberSil(HelpAsCompanyApp.SonService.HaberSilRequest request) {
            return base.Channel.HaberSil(request);
        }
        
        public string HaberSil(int haber_id) {
            HelpAsCompanyApp.SonService.HaberSilRequest inValue = new HelpAsCompanyApp.SonService.HaberSilRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.HaberSilRequestBody();
            inValue.Body.haber_id = haber_id;
            HelpAsCompanyApp.SonService.HaberSilResponse retVal = ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).HaberSil(inValue);
            return retVal.Body.HaberSilResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.HaberSilResponse> HelpAsCompanyApp.SonService.WebService1Soap.HaberSilAsync(HelpAsCompanyApp.SonService.HaberSilRequest request) {
            return base.Channel.HaberSilAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.HaberSilResponse> HaberSilAsync(int haber_id) {
            HelpAsCompanyApp.SonService.HaberSilRequest inValue = new HelpAsCompanyApp.SonService.HaberSilRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.HaberSilRequestBody();
            inValue.Body.haber_id = haber_id;
            return ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).HaberSilAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelpAsCompanyApp.SonService.HaberGüncelleResponse HelpAsCompanyApp.SonService.WebService1Soap.HaberGüncelle(HelpAsCompanyApp.SonService.HaberGüncelleRequest request) {
            return base.Channel.HaberGüncelle(request);
        }
        
        public string HaberGüncelle(int haber_id, string haber_baslik, string haber_icerik) {
            HelpAsCompanyApp.SonService.HaberGüncelleRequest inValue = new HelpAsCompanyApp.SonService.HaberGüncelleRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.HaberGüncelleRequestBody();
            inValue.Body.haber_id = haber_id;
            inValue.Body.haber_baslik = haber_baslik;
            inValue.Body.haber_icerik = haber_icerik;
            HelpAsCompanyApp.SonService.HaberGüncelleResponse retVal = ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).HaberGüncelle(inValue);
            return retVal.Body.HaberGüncelleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.HaberGüncelleResponse> HelpAsCompanyApp.SonService.WebService1Soap.HaberGüncelleAsync(HelpAsCompanyApp.SonService.HaberGüncelleRequest request) {
            return base.Channel.HaberGüncelleAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelpAsCompanyApp.SonService.HaberGüncelleResponse> HaberGüncelleAsync(int haber_id, string haber_baslik, string haber_icerik) {
            HelpAsCompanyApp.SonService.HaberGüncelleRequest inValue = new HelpAsCompanyApp.SonService.HaberGüncelleRequest();
            inValue.Body = new HelpAsCompanyApp.SonService.HaberGüncelleRequestBody();
            inValue.Body.haber_id = haber_id;
            inValue.Body.haber_baslik = haber_baslik;
            inValue.Body.haber_icerik = haber_icerik;
            return ((HelpAsCompanyApp.SonService.WebService1Soap)(this)).HaberGüncelleAsync(inValue);
        }
    }
}
