//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace HelpAsCompanyApp.WebReferenceHelpAs {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="HelpAsServiceSoap", Namespace="http://tempuri.org/")]
    public partial class HelpAsService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SehirListesiOperationCompleted;
        
        private System.Threading.SendOrPostCallback IlceListesiOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlanListesiOperationCompleted;
        
        private System.Threading.SendOrPostCallback AltAlanListesiOperationCompleted;
        
        private System.Threading.SendOrPostCallback UstaEklemeOperationCompleted;
        
        private System.Threading.SendOrPostCallback DenemeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public HelpAsService() {
            this.Url = "http://192.168.2.45:52489/HelpAsService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SehirListesiCompletedEventHandler SehirListesiCompleted;
        
        /// <remarks/>
        public event IlceListesiCompletedEventHandler IlceListesiCompleted;
        
        /// <remarks/>
        public event AlanListesiCompletedEventHandler AlanListesiCompleted;
        
        /// <remarks/>
        public event AltAlanListesiCompletedEventHandler AltAlanListesiCompleted;
        
        /// <remarks/>
        public event UstaEklemeCompletedEventHandler UstaEklemeCompleted;
        
        /// <remarks/>
        public event DenemeCompletedEventHandler DenemeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SehirListesi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SehirListesi() {
            object[] results = this.Invoke("SehirListesi", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SehirListesiAsync() {
            this.SehirListesiAsync(null);
        }
        
        /// <remarks/>
        public void SehirListesiAsync(object userState) {
            if ((this.SehirListesiOperationCompleted == null)) {
                this.SehirListesiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSehirListesiOperationCompleted);
            }
            this.InvokeAsync("SehirListesi", new object[0], this.SehirListesiOperationCompleted, userState);
        }
        
        private void OnSehirListesiOperationCompleted(object arg) {
            if ((this.SehirListesiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SehirListesiCompleted(this, new SehirListesiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IlceListesi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string IlceListesi(string Sehir_Ismi) {
            object[] results = this.Invoke("IlceListesi", new object[] {
                        Sehir_Ismi});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void IlceListesiAsync(string Sehir_Ismi) {
            this.IlceListesiAsync(Sehir_Ismi, null);
        }
        
        /// <remarks/>
        public void IlceListesiAsync(string Sehir_Ismi, object userState) {
            if ((this.IlceListesiOperationCompleted == null)) {
                this.IlceListesiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIlceListesiOperationCompleted);
            }
            this.InvokeAsync("IlceListesi", new object[] {
                        Sehir_Ismi}, this.IlceListesiOperationCompleted, userState);
        }
        
        private void OnIlceListesiOperationCompleted(object arg) {
            if ((this.IlceListesiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IlceListesiCompleted(this, new IlceListesiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AlanListesi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AlanListesi() {
            object[] results = this.Invoke("AlanListesi", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AlanListesiAsync() {
            this.AlanListesiAsync(null);
        }
        
        /// <remarks/>
        public void AlanListesiAsync(object userState) {
            if ((this.AlanListesiOperationCompleted == null)) {
                this.AlanListesiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlanListesiOperationCompleted);
            }
            this.InvokeAsync("AlanListesi", new object[0], this.AlanListesiOperationCompleted, userState);
        }
        
        private void OnAlanListesiOperationCompleted(object arg) {
            if ((this.AlanListesiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlanListesiCompleted(this, new AlanListesiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AltAlanListesi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AltAlanListesi(string Alan_İsmi) {
            object[] results = this.Invoke("AltAlanListesi", new object[] {
                        Alan_İsmi});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AltAlanListesiAsync(string Alan_İsmi) {
            this.AltAlanListesiAsync(Alan_İsmi, null);
        }
        
        /// <remarks/>
        public void AltAlanListesiAsync(string Alan_İsmi, object userState) {
            if ((this.AltAlanListesiOperationCompleted == null)) {
                this.AltAlanListesiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAltAlanListesiOperationCompleted);
            }
            this.InvokeAsync("AltAlanListesi", new object[] {
                        Alan_İsmi}, this.AltAlanListesiOperationCompleted, userState);
        }
        
        private void OnAltAlanListesiOperationCompleted(object arg) {
            if ((this.AltAlanListesiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AltAlanListesiCompleted(this, new AltAlanListesiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UstaEkleme", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UstaEkleme(string Alan_İsmi) {
            object[] results = this.Invoke("UstaEkleme", new object[] {
                        Alan_İsmi});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UstaEklemeAsync(string Alan_İsmi) {
            this.UstaEklemeAsync(Alan_İsmi, null);
        }
        
        /// <remarks/>
        public void UstaEklemeAsync(string Alan_İsmi, object userState) {
            if ((this.UstaEklemeOperationCompleted == null)) {
                this.UstaEklemeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUstaEklemeOperationCompleted);
            }
            this.InvokeAsync("UstaEkleme", new object[] {
                        Alan_İsmi}, this.UstaEklemeOperationCompleted, userState);
        }
        
        private void OnUstaEklemeOperationCompleted(object arg) {
            if ((this.UstaEklemeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UstaEklemeCompleted(this, new UstaEklemeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Deneme", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Deneme(int shr_id) {
            object[] results = this.Invoke("Deneme", new object[] {
                        shr_id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DenemeAsync(int shr_id) {
            this.DenemeAsync(shr_id, null);
        }
        
        /// <remarks/>
        public void DenemeAsync(int shr_id, object userState) {
            if ((this.DenemeOperationCompleted == null)) {
                this.DenemeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDenemeOperationCompleted);
            }
            this.InvokeAsync("Deneme", new object[] {
                        shr_id}, this.DenemeOperationCompleted, userState);
        }
        
        private void OnDenemeOperationCompleted(object arg) {
            if ((this.DenemeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DenemeCompleted(this, new DenemeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SehirListesiCompletedEventHandler(object sender, SehirListesiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SehirListesiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SehirListesiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void IlceListesiCompletedEventHandler(object sender, IlceListesiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IlceListesiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IlceListesiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AlanListesiCompletedEventHandler(object sender, AlanListesiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AlanListesiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AlanListesiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AltAlanListesiCompletedEventHandler(object sender, AltAlanListesiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AltAlanListesiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AltAlanListesiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void UstaEklemeCompletedEventHandler(object sender, UstaEklemeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UstaEklemeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UstaEklemeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DenemeCompletedEventHandler(object sender, DenemeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DenemeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DenemeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591